### ISSUE TITLE
glitch.io issue

### ISSUE THREAD

**Issue by HavenDV** [HavenDV/H.Socket.IO#11]
Hi! How are you?

I'm doing some tests with your project  https://www.nuget.org/packages/H.Socket.IO/. it's very good, thank you very much for sharing it!

I can't connect to a server.io located at glitch.io
ws://verne-socket.glitch.me/

Here you can see the server code in glitch.io
https://glitch.com/edit/#!/verne-socket?path=server.js%3A1%3A0

However if I can connect correctly to the address you use in the Chat Demo 
 "wss://socketio-chat-h9jt.herokuapp.com/ " 

I understand that the server code is:
 https://github.com/HavenDV/H.Socket.IO/blob/master/src/TestServers/Socket.IO.ChatExample/chat.js, 

I do not find many differences, so I ask you: do you have to make a special configuration for it to work? do you think it doesn't work because it's hosted on glitch.io? I would love to have your opinion to understand what is happening and learn, 

Thank you very much.
Cheers!

Bernardo.

**Comment by HavenDV** [comment]
The problem was not resolved quickly. I'll do it as soon as I have free time.
So far I think this server requires some required headers to be set.
It would help a lot if you start the server locally and connect to it via a path like ws://localhost:1465/

**Comment by obernardoo** [comment]
Hi! the server works fine locally. We also did the test of passing the same server to a heroku app, and the connection works fine. So it's something between this library with glitch.io
