### ISSUE TITLE
How do I set namespace and custom path?

### ISSUE THREAD

**Issue by phillijw** [HavenDV/H.Socket.IO#12]
Is there any ability to connect using a namespace and a path similar to what is shown on this page? https://socket.io/docs/v3/client-api/index.html#With-custom-path

As you can see, the syntax used there is to put the namespace (admin) in the URL and then pass in a custom path: 

```
const socket = io('http://localhost/admin', {
  path: '/mypath'
});
```

**Comment by phillijw** [comment]
30 seconds later I realize the path is specified on the `On` handler 👍 

```
client.On("stream", MyEventHandler.handler, "myPath");
```

**Comment by HavenDV** [comment]
Updated README according to this.
