### ISSUE TITLE
socket io v2

### ISSUE THREAD

**Issue by yamidevs** [HavenDV/H.Socket.IO#16]
Hello, I would like to try to communicate with a server that uses socket.io v2, but I can't with the library, I can connect and all but the emit and the on don't work
so is it possible to connect with the library ?
this is the server I want to connect to and thank you!
https://github.com/mxcdevelop/APIDoc/blob/master/websocket/spot/websocket-api.md

**Comment by HavenDV** [comment]
At the moment, this is not available. The library was written for server version 3 or 4.
I can do paid support for you, or you can just search GitHub for alternatives.
