### ISSUE TITLE
TLS version

### ISSUE THREAD

**Issue by EmilPoulsen** [HavenDV/H.Socket.IO#19]
Hi @HavenDV,
Many thanks for creating this great library. I've done some testing to get it connected to a socket.io based node server, and it seems to work fine 👍 

Just had a question regarding [TLS](https://en.wikipedia.org/wiki/Transport_Layer_Security) - is it possible to configure what version of TLS that will be used to send/receive messages to/from a node server? Right now it seems like TLS v1.2 is used in my test environment.

Thanks again! 🙏

**Comment by HavenDV** [comment]
Hello. 

https://stackoverflow.com/a/59388323

**Comment by EmilPoulsen** [comment]
Thank you! I will try that.
