### ISSUE TITLE
adding rooms 

### ISSUE THREAD

**Issue by waltergrimmvie** [HavenDV/H.Socket.IO#5]
Thanxs for your effort to create this tool, and the samples. I have a question please.

Your page states that namespaces have been introduced. Does your tool also support the room function, join on and emit to rooms?

thanxs very much

**Comment by HavenDV** [comment]
I will do this as soon as my free time appears.
It will be great if you can provide test code like the [one](https://github.com/HavenDV/H.Socket.IO/blob/master/Servers/Socket.IO.ChatExample/custom-namespaces.js) on which I can test the solution

**Comment by waltergrimmvie** [comment]
HI Konstantin

I would be glad if you could help me to create one basic sample for VB to login with SSL and add some on and emit functions

We are using the Laravel Echo server and ist working fine with JS.

Of course I will pay you for your kind effort.

thanxs

regards

Dr. Walter Grimm

Mobile: +43 699 127 56 228
Mail: grimm@q-auditors.com<mailto:grimm@q-auditors.com>
Web: http://www.quality-auditors.com<http://www.quality-auditors.com/>
Orchisgasse 27, 1220 – Wien - Österreich

Von: Konstantin S. <notifications@github.com>
Gesendet: Mittwoch, 20. Mai 2020 17:20
An: HavenDV/H.Socket.IO <H.Socket.IO@noreply.github.com>
Cc: Walter Grimm | Q-Auditors <grimm@q-auditors.com>; Author <author@noreply.github.com>
Betreff: Re: [HavenDV/H.Socket.IO] adding rooms (#5)


I will do this as soon as my free time appears.
It will be great if you can provide test code like the one<https://github.com/HavenDV/H.Socket.IO/blob/master/Servers/Socket.IO.ChatExample/custom-namespaces.js> on which I can test the solution

**Comment by waltergrimmvie** [comment]
HI,

you have the code for laravel echo in C#. I will be using VB.NET. Can we create a dll with the functions for accessing the socket server, or convert the code from C# to VB (therr are sites that convert it).

Please give me a suggestion and time price estimate (one VB Demo project) with call function on server and recieve strign from server.

We have a laravel Echo SSL server running, where users get signed into a room, emit and recieve string.

Walter G.


regards

Dr. Walter Grimm

Mobile: +43 699 127 56 228
Mail: grimm@q-auditors.com<mailto:grimm@q-auditors.com>
Web: http://www.quality-auditors.com<http://www.quality-auditors.com/>
Orchisgasse 27, 1220 – Wien - Österreich

Von: Konstantin S. <notifications@github.com>
Gesendet: Mittwoch, 20. Mai 2020 17:20
An: HavenDV/H.Socket.IO <H.Socket.IO@noreply.github.com>
Cc: Walter Grimm | Q-Auditors <grimm@q-auditors.com>; Author <author@noreply.github.com>
Betreff: Re: [HavenDV/H.Socket.IO] adding rooms (#5)


I will do this as soon as my free time appears.
It will be great if you can provide test code like the one<https://github.com/HavenDV/H.Socket.IO/blob/master/Servers/Socket.IO.ChatExample/custom-namespaces.js> on which I can test the solution

**Comment by HavenDV** [comment]
https://stackoverflow.com/questions/40367765/joining-socket-io-room-on-connect
There is no `.join()` method on the client side. Rooms are purely a server-side construct and the client knows nothing about them.

Your first block of code is the desired way to do things. You send the server a message of your design asking it to join the socket to a room and the `.join()` is executed on the server side.

**Comment by waltergrimmvie** [comment]
Thanx,

Let's just start a project, I don't want any free stuff,  want to get it running with vb. Net

Please give me a quote to get laravel echo running with VB on a running server with JS

Thanx

Sent from Nine<http://www.9folders.com/>
________________________________
Von: "Konstantin S." <notifications@github.com>
Gesendet: Donnerstag, 21. Mai 2020 16:58
An: HavenDV/H.Socket.IO
Cc: Walter Grimm | Q-Auditors; Author
Betreff: Re: [HavenDV/H.Socket.IO] adding rooms (#5)


https://stackoverflow.com/questions/40367765/joining-socket-io-room-on-connect
There is no .join() method on the client side. Rooms are purely a server-side construct and the client knows nothing about them.

Your first block of code is the desired way to do things. You send the server a message of your design asking it to join the socket to a room and the .join() is executed on the server side.

**Comment by HavenDV** [comment]
I have prepared an example for you
VB.NET .NET Fiddle - https://dotnetfiddle.net/3VJWRc

**Comment by HavenDV** [comment]
I updated the example to use Async/Await: https://dotnetfiddle.net/WzIdnG

**Comment by waltergrimmvie** [comment]
HI Konstantin,

Without wanting to bother you more, your sample is great and works fine,

We are using Laravel Echo which is based on socket.io, and apparently can be used 1:1

Can we please set up a project, so you can assist me in getting your code running with our Server: This is how we access the server from JS:

import Echo from 'laravel-echo'

window.Pusher = require('pusher-js');

window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    cluster: process.env.MIX_PUSHER_APP_CLUSTER,
    wsPort: 6001,
    wsHost: window.location.hostname,
    encrypted: true,
    wssPort: 6001,
    disableStats:true,
    enabledTransports: ['ws', 'wss'],
});



regards

Dr. Walter Grimm
Von: Konstantin S. <notifications@github.com>
Gesendet: Freitag, 22. Mai 2020 01:54
An: HavenDV/H.Socket.IO <H.Socket.IO@noreply.github.com>
Cc: Walter Grimm | Q-Auditors <grimm@q-auditors.com>; Author <author@noreply.github.com>
Betreff: Re: [HavenDV/H.Socket.IO] adding rooms (#5)


I updated the example to use Async/Await: https://dotnetfiddle.net/WzIdnG

**Comment by HavenDV** [comment]
https://www.upwork.com/fl/havendv
You can hire me here if you need a turnkey solution specifically for you. Laravel Echo is a wrapper for Socket.IO, but nonetheless, I need time to adapt the current solution for your project. And most likely, I need to create a separate library for this.
