### ISSUE TITLE
Url with path

### ISSUE THREAD

**Issue by sedashgh** [HavenDV/H.Socket.IO#6]
If you are connecting to a socket.io server whose url is https://abc.com/path one simply gets a 200 response instead of 101. This is because of code in EngineIOClient.OpenAsync Line 300:
var socketIoUri = new Uri($"{scheme}://{Uri.Host}:{Uri.Port}/{Framework}/?EIO=3&transport=websocket&{Uri.Query.TrimStart('?')}");
Possible fix which I am using locally is
            string path = string.Empty;
            for (int i = 1; i < Uri.Segments.Length; i++)
                path += Uri.Segments[i];
            if (path.Length > 0 && !path.EndsWith("/"))
                path += "/";
            var socketIoUri = new Uri($"{scheme}://{Uri.Host}:{Uri.Port}/{path}{Framework}/?EIO=3&transport=websocket&{Uri.Query.TrimStart('?')}");

**Comment by HavenDV** [comment]
Hello. Thanks for reporting this error.
I am currently creating tests to remove this error. Can you give an example of how it should be?

```cs

**Comment by HavenDV** [comment]
Is it correct?
```cs
ToWebSocketUriBaseTest(
    "wss://abc.com/path/socket.io/?EIO=3&transport=websocket&",
    "https://abc.com/path",
    "socket.io");
```

**Comment by sedashgh** [comment]
Yes. Although you might want as well the following:
"https://abc.com/path?arg"
"https://abc.com/path/?arg
"https://abc.com?arg"
"https://abc.com/?arg

Best regards
David

**Comment by HavenDV** [comment]
At the moment, this has already been implemented:
```cs
ToWebSocketUriBaseTest(
    "wss://abc.com/path/engine.io/?EIO=3&transport=websocket&arg=value",
    "https://abc.com/path/?arg=value");
ToWebSocketUriBaseTest(
    "wss://abc.com/path/engine.io/?EIO=3&transport=websocket&arg",
    "https://abc.com/path?arg");
ToWebSocketUriBaseTest(
    "wss://abc.com/engine.io/?EIO=3&transport=websocket&arg",
    "https://abc.com?arg");
ToWebSocketUriBaseTest(
    "wss://abc.com/engine.io/?EIO=3&transport=websocket&arg",
    "https://abc.com/?arg");
```

**Comment by sedashgh** [comment]
Great! Fantastic library BTW.

**Comment by HavenDV** [comment]
I made a release, soon it will be available on NuGet. Please check and report if there are any problems.

**Comment by sedashgh** [comment]
Just updated from nuget to 1.0.3 and it works fine.
Thanks
David
